from .home_page import HomePage
from .single.single_choose_mode_page import SingleChooseModePage
from .game_page import GamePage
from .single.single_new_page import SingleNewPage
from .single.single_game_page import SingleGamePage
from .multi.multi_remote_page import MultiRemotePage
from .multi.multi_game_page import MultiGamePage
from .multi.multi_choose_mode_page import MultiChooseModePage
from .multi.multi_local_choose_mode_page import MultiLocalChooseModePage
from .multi.multi_local_new_page import MultiLocalNewPage
